after [Code] [`packages/stdkjs/package.json`] [`scripts`] these temporary removal of these items, since we're ReHisting ("Rebasing"), to avoid 'Merge Conflict'(s); partially reverting what Commit `747875383a61f167880b6c028c80f8916f14dcd6` did to the file (`packages/stdkjs/package.json`), and to be Re-Inst-Ed sometime later one
```
Executing: git restore --staged --worktree --source=747875383a61f167880b6c028c80f8916f14dcd6~1 -- packages/stdkjs/package.json
error: cannot rebase: Your index contains uncommitted changes.
warning: execution succeeded: git restore --staged --worktree --source=747875383a61f167880b6c028c80f8916f14dcd6~1 -- packages/stdkjs/package.json
but left changes to the index and/or the working tree
Commit or stash your changes, and then run

  git rebase --continue

```